### ISSUE TITLE
Fatal error while downloading the overlay data (Ubuntu, RStudio 1.4.1106)

### ISSUE THREAD

**Issue by tifa365** [h-a-graham/rayvista#2]
Fatal error message pops up on the screen and R sessions can only be restarted. Happends with any of the given examples.

**Comment by h-a-graham** [comment]
Pretty sure this is a RAM issue. Can you try setting lower values for 'overlay_detail' and possibly 'elevation_detail'? Can you also let me know how much RAM you have installed? I should perhaps lower the default values or provide examples with lower memory requirements. 

Thanks

**Comment by tifa365** [comment]
Different error now.

`> library(rayshader)
> library(rayvista)
> HopkinsNZ <- plot_3d_vista(lat=-44.042238, long=169.860985, radius=5000, overlay_detail = 2,
+                            elevation_detail=2, zscale=5, img_provider = 'OpenStreetMap',
+                            cache_dir = 'testing',theta=25, phi=25, zoom=0.5,
+                            windowsize =1200, solid=T, background='grey10')
Donloading Overlay...
Fehler in curl::curl_download(url = q, destfile = outfile) : 
  Failed to open file testing/rayvista_cache/OpenStreetMap/OpenStreetMap_2_3_2.png.curltmp.
Zusätzlich: Warnmeldungen:
1: In dir.create(cache_sub) :
  kann Verzeichnis 'testing/rayvista_cache' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'
2: In dir.create(cachedir) :
  kann Verzeichnis 'testing/rayvista_cache' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'
3: In dir.create(subdir) :
  kann Verzeichnis 'testing/rayvista_cache/OpenStreetMap' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'`

**Comment by h-a-graham** [comment]
Thanks again! Do you mind trying the following:

`HopkinsNZ <- plot_3d_vista(lat=-44.042238, long=169.860985, radius=5000, overlay_detail = 10,
                           elevation_detail=10, zscale=20, img_provider = 'OpenStreetMap',
                           cache_dir = 'testing',theta=25, phi=25, zoom=0.5,
                           windowsize =1200, solid=T, background='grey10')`

The scale of this download should be fine for any amount of RAM. There seems to be some stange issues relating to very low res downloads.

Also, do you mind sharing your `sessionInfo()` ?

Cheers!

**Comment by tifa365** [comment]
```
Donloading Overlay...
Fehler in curl::curl_download(url = q, destfile = outfile) : 
  Failed to open file testing/rayvista_cache/OpenStreetMap/OpenStreetMap_10_995_651.png.curltmp.
Zusätzlich: Warnmeldungen:
1: In dir.create(cache_sub) :
  kann Verzeichnis 'testing/rayvista_cache' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'
2: In dir.create(cachedir) :
  kann Verzeichnis 'testing/rayvista_cache' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'
3: In dir.create(subdir) :
  kann Verzeichnis 'testing/rayvista_cache/OpenStreetMap' nicht erzeugen. Grund 'Datei oder Verzeichnis nicht gefunden'
```

**Comment by h-a-graham** [comment]
OKay... i might have an idea. Are you running this from an R project? Have you tried this without specifying the cache directory? as in: 
`HopkinsNZ <- plot_3d_vista(lat=-44.042238, long=169.860985, radius=5000, overlay_detail = 10, elevation_detail=10, zscale=20, img_provider = 'OpenStreetMap', theta=25, phi=25, zoom=0.5, windowsize =1200, solid=T, background='grey10')
`

**Comment by tifa365** [comment]
That seemed to work, I'll get the HopkinsNZ variable. How do I actually see the end result? `render_snapshot(clear=TRUE)` just produces a black image.

**Comment by h-a-graham** [comment]
So when you run `plot_3d_vista`, does this open an rgl window with the 3d scene?
using:
`render_snapshot(clear=FALSE)`
might save you needing to re run the plot_3d_vista function...

**Comment by tifa365** [comment]
I'll get another error.

```
render snapshot could not be found
```
Activating rayshader produces an empty, black box.

If I try to install the rgl package on top:

```
In rgl.snapshot(filename, fmt, top) :
  this build of rgl does not support snapshots
```

**Comment by h-a-graham** [comment]
Okay, that's helpful. But does the 3d scene appear in a new external window after running plot_3d_vista? If this works as you expect, I think the issue is with the way you have installed rgl. Check the instructions here for more information if so. 

However, if the function plot_3d_vista is not producing a new external window with the desired 3d view please let me know. 
Thanks

**Comment by tifa365** [comment]
There's no window opening up. When I load all three packages (rayshader, rayvista, rayrender) at least the rending seems to start but crashes R, again the RAM issue I suppose (even with the last examle).

**Comment by h-a-graham** [comment]
Sorry I meant to share this link: https://dmurdoch.github.io/rgl/dev/ which gives some good instructions on how to install rgl and some of necessary prerequisites. Have you tried the examples on the rayshader GitHub page? Do these work for you? If I were you I would try to get rgl working with render_snapahot as this is so much faster than render_highquality.

**Comment by h-a-graham** [comment]
Another thing which may help is the recent update to {maptiles}. The large RAM usage is now fixed and so your session shouldn't rash when creating the 3D scene. Just update maptiles to the latest develeopment version like so:

```
# install.packages("remotes")
remotes::install_github("riatelab/maptiles")
```

**Comment by tifa365** [comment]
Thanks! I gave the HopkinsNZ code you provided another shot and it indeed works with `rglwidget()`! `render_snapshot(clear=TRUE)` not functioning seems to be a problem with the rayshader package sind I was running into problems with those code examples as well.
