### ISSUE TITLE
bounds object not recognised

### ISSUE THREAD

**Issue by joelfiddes** [h-a-graham/rayvista#28]
Hi there, this is a really geat looking package and have just been playing with a fresh install, however, I am getting an error with the crop function:

Seems like the bounds object generated here in download_elevation.R:
`bounds <- sf::st_bbox(bounds_sf)`

is not recognised as the crop function then throws:
 `Error in .local(x, y, ...) : Cannot get an Extent object from argument y`

Fine with all other elevation datasets args - just applies to "aws" where you have the patch from commit:
https://github.com/h-a-graham/rayvista/commit/9ae923c99d67265d93c8c5c5afad0f2c4dde480b

Thanks!

R version 3.6.3

**Comment by joelfiddes** [comment]
Hi Graham thanks for looking into it and looks like you've solved it. Your test does indeed throw an error and I have raster_3.0-7 sp_1.4-4 running. Apologies, I should have thought of this!

**Comment by h-a-graham** [comment]
No problem at all! It's very helpful actually, I'll add the version number as a minimum dependency. Thanks very much.

**Comment by h-a-graham** [comment]
OKay so I've added the minimum raster dep here:m https://github.com/h-a-graham/rayvista/pull/29 

I'll close this issue for now but please reopen if the problem persists. 

Many thanks!
