### ISSUE TITLE
render_highquality(clear = TRUE) not working

### ISSUE THREAD

**Issue by sgsalmo** [h-a-graham/rayvista#7]
Hi again, Hugh!

I tried the rayvista package again, in one of my sites. The render function works. But, when I use "render_highquality(clear = TRUE), my R stops with an error message, as:

<img width="439" alt="R Session Aborted" src="https://user-images.githubusercontent.com/80515793/118653150-d01a2680-b819-11eb-9439-3996af8fa79a.png">

Thanks,

SS

**Comment by h-a-graham** [comment]
This could be for a couple of different reasons... I would try reinstalling rayshader from github like so: 
`devtools::install_github("tylermorganwall/rayshader")`
then try again. 
If it still isn't working then It may be that the resolution of the scene is too large for your computer's resources. If that is the case, trying a smaller or lower resolution example may help.
Good luck!

**Comment by sgsalmo** [comment]
Hi Hugh!

Yes, the code works after I reduced the resolution.

Thanks again!

SS
